### ISSUE TITLE
RA manual updates

### ISSUE THREAD

**Issue by norrissam** [norrissam/ra-manual#2]
1/ get rid of git-lfs references in RA manual

2/ say that an issue should be resolved with a deliverable or a wiki change.

3/ put in manual that we should have a branch to delete old/unnecessary code very 2 months

4/ 2 space tabs

5/ refer to notes section in wiki for references that are outside project

6/ refer to facts subfolder in exhibits to contain facts from the data in csvs (e.g., share of prisoners ever sent to SC).

7/ make it clear that the restirction on commit messages is for the squash commit (matt)

8/ take out references to Make Paper.sh, version command (stata), and object oriented programming

**Comment by voldermatt** [comment]
Made all edits.
